version: '3.8'

services:
  porstgres:
    container_name: course-crud
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=course-crud-postgres